* Rincewind's Doom
** Why Doom?
Doom emacs is what i wanted when i first installed spacemacs.
Doom emacs is what i wanted to make when i started my own config
Doom emacs (with a few personal tweaks) is pretty much the editor i've always wanted
** Who is this for?
Mostly myself.
I am a CS Student, my main languages are C and C++ most of the time. I also like to
use ruby as my general "Glue" language for short scripts and the like.

I am currently learning lisp, and very much enjoy writing it, i feel it may take ruby's place at some point.

I also am currently learning Hasekll becuase monads are fun.

I write as much prose as i have to write as LaTeX documents, and take my lecture notes in org-mode.
** How does this config work? Where's your config.el?
I use org-mode and org-babel to extract the code from the very document you are reading now. All of the codeblocks are
"Untangled" by org at bootup time. This adds a bit to the startup time of emacs, but only about 0.4 seconds, this is a fine tradeoff
as far as i'm concerened. I'd rather have maintainable configs than go through dotfile bankruptcy
* General Keybinds
Keybinds for managing windows, Buffers and meta-config related functions
** Windows
*** Move
#+BEGIN_SRC emacs-lisp
(map!
 :ne "C-w <right>" #'evil-window-right
 :ne "C-w <left>"  #'evil-window-left
 :ne "C-w <up>"    #'evil-window-up
 :ne "C-w <down>"  #'evil-window-down
 )
#+END_SRC
*** Splits
#+BEGIN_SRC emacs-lisp
(map!
 (:leader
   (:prefix "w"
     :desc "vsplit" :nv "/" #'evil-window-vsplit
     :desc "hsplit" :nv "-" #'evil-window-split)))
#+END_SRC
*** Deletes
#+BEGIN_SRC emacs-lisp
(map!
 (:leader
   (:prefix "w"
     :desc "Delete window" :n "d" #'evil-window-delete
     :desc "Kill Win+Buf"  :n "q" #'kill-buffer-and-window)))
#+END_SRC
** Buffers
#+BEGIN_SRC emacs-lisp
(map!
 (:leader
   (:prefix "b"
     :desc "Kill Buffer" :n "d" #'kill-this-buffer
     :desc "Kill buffer" :n "q" #'kill-this-buffer)))
#+END_SRC
** Open config.org
#+BEGIN_SRC emacs-lisp
(defun rncwind-visit-config ()
  (interactive)
  (find-file "~/.doom.d/config.org"))

(map! (:leader (:prefix "h"
                 :desc "Open config.org" :n "C" #'rncwind-visit-config)))
#+END_SRC
** Reload config.org
#+BEGIN_SRC emacs-lisp
(defun rncwind-reload-config ()
  (interactive)
  (org-babel-load-file (expand-file-name "~/.doom.d/config.org")))

(map! (:leader (:prefix "h"
                 :desc "Reload config.org" :n "R" #'rncwind-reload-config)))
#+END_SRC
* Misc Tweaks
Various tweaks that don't need their own section
** Set font
#+BEGIN_SRC emacs-lisp
(setq doom-font (font-spec :family "hack" :size 14)
      doom-variable-pitch-font (font-spec :family "Noto Sans")
      doom-unicode-font (font-spec :family "hack")
      doom-big-font (font-spec :family "hack" :size 20))
#+END_SRC
* General Programming
General tweaks but for programming
** Use Emacs 26 line numbers
#+BEGIN_SRC emacs-lisp
(setq-default doom-line-numbers-style 'relative)
(add-hook 'prog-mode-hook 'display-line-numbers-mode)
#+END_SRC
* Ivy
Apparently better than helm. I'm trying it out
** <leader>ff find file keybind
#+BEGIN_SRC emacs-lisp
(map! :after ivy-mode
      :leader
      (:prefix "f"
        :desc "Find File" :nv "f" #'counsel-find-file))
#+END_SRC
** Switch buffers
#+BEGIN_SRC emacs-lisp
(map! :after ivy-mode
      :leader 
      (:prefix "b"
        :desc "Switch Buffer" :nv "b" #'ivy-switch-buffer))
#+END_SRC
* C/C++
My main squeeze. Package config for irony/ctags. As well as other general QOL type things
** irony and rtags
#+BEGIN_SRC emacs-lisp
(add-hook 'c++-mode-hook 'irony-mode)
(add-hook 'c-mode-hook 'irony-mode)
#+END_SRC
** Default compiler options
#+BEGIN_SRC emacs-lisp
(setq-default +cc-default-compiler-options
              '((c-mode   "-std=c11" nil)
                (c++-mode "-std=c++17" nil)))
#+END_SRC
** Clang-format
#+BEGIN_SRC emacs-lisp
(map! :after cc-mode
      :map c++-mode-map
      :localleader
      (:desc "clang-format" :prefix "f"
        :desc "clang-format Buffer" :n "b" #'clang-format-buffer
        :desc "clang-format Region" :n "r" #'clang-format-region))
#+END_SRC
* Ruby
Becuase if i'm not using c or lisp, i dont care about speed and want something to make me happy
* Lisps
((((lisp))))
* Haskell
A monad is just a monoid in the category of endofunctors, what's the probleⅿ?
