THIS IS A WORK IN PROGRESS
THIS CONFIG FILE IS NOT SUITABLE FOR ACTIVE USAGE
IT IS IN SOURCE CONTROL FOR PRODUCTIVITY REASONS
DO NOT SOURCE IT AS A DAILY DRIVER
* Misc
  Small misc tweaks and packages that dont need their own category
** change yes-or-no to y-or-n
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Fix emacs shitty default scrolling
#+BEGIN_SRC emacs-lisp
  (setq scroll-conservatively 100)
#+END_SRC
** Disable ring bell so i dont shit my pants
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore) 
#+END_SRC
** Enable line hilight
#+BEGIN_SRC emacs-lisp
  (when window-system (global-hl-line-mode t))
#+END_SRC
** Disable backups and autosaves
#+BEGIN_SRC emacs-lisp
  (setq make-backup-file nil)
  (setq auto-save-default nil)
#+END_SRC
** Enable line numbers
#+BEGIN_SRC emacs-lisp
  ;;Use linum-off as a lazy way of disabling stuff in a bunch of modes that dont need it
  (use-package linum-off
    :ensure t)
  (global-linum-mode t)
#+END_SRC
* Rice
  The Structure And Interpretation Of Riced Text Editors
** GUI Bullshit
*** Disable toolbar
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
#+END_SRC
*** Disable menu bar
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
#+END_SRC
*** Disable scroll bar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
#+END_SRC
*** Disable default emacs startup screen
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC
** Dashboard
   Dashboard is great. It looks nice and it's convinient.
#+BEGIN_SRC emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-items '((recents . 10)))
    (setq dashboard-banner-logo-title "Structure And Interepretation of Riced Text Editors"))
#+END_SRC
** spaceline
   The default emacs modeline is horrible. Powerline is lacking. Spaceline is good
#+BEGIN_SRC emacs-lisp
  (use-package spaceline
    :ensure t
    :config
    (require 'spaceline-config)
    (setq-default powerline-default-seperator (quote arrow-fade))
    (spaceline-spacemacs-theme))
#+END_SRC
* Org
  Org is amazing. Config and packages for it go here. If you dont like org, i dont want to be your freind
** Org Bullets
   Add some pretty bullet points instead of *s everywhere
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode))))
#+END_SRC
* Evil
  I use evil mode becuase i still firmly beleive that modal editing is the best editing experience and i want to keep that in emacs
** Disable integration for evil collection
#+BEGIN_SRC emacs-lisp
  (setq evil-want-integration nil)
#+END_SRC
** evil-leader
   Use evil leader. map leader on <SPC>
#+BEGIN_SRC emacs-lisp
  (use-package evil-leader
    :ensure t
    :init (setq evil-leader/in-all-states t) (global-evil-leader-mode)
    :config (evil-leader/set-leader "<SPC>"))
#+END_SRC
** evil itself
#+BEGIN_SRC emacs-lisp
  (use-package evil
    :ensure t
    :config
    (evil-mode 1))
#+END_SRC
** evil-escape
#+BEGIN_SRC emacs-lisp
  (use-package evil-escape
    :ensure t
    :init
    (evil-escape-mode))
#+END_SRC
** evil-collection
#+BEGIN_SRC emacs-lisp
(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))
#+END_SRC
** Window keybinds
*** Splits
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
    "w/" 'evil-window-vsplit)
  (evil-leader/set-key
    "w-" 'evil-window-split)
#+END_SRC
*** Deletes
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
    "wd" 'evil-window-delete)
  (evil-leader/set-key
    "wx" 'kill-buffer-and-window)
  (evil-leader/set-key
    "wo" 'delete-other-windows)
#+END_SRC
*** Moves
#+BEGIN_SRC emacs-lisp
  (define-key evil-normal-state-map
    (kbd "C-w <left>") 'evil-window-left)

  (define-key evil-normal-state-map
    (kbd "C-w <right>") 'evil-window-right)

  (define-key evil-normal-state-map
    (kbd "C-w <up>") 'evil-window-up)

  (define-key evil-normal-state-map
    (kbd "C-w <down>") 'evil-window-down)
#+END_SRC
* QOL
  Quality of life packages and other miscelany that i find useful
** which-key
   Enable which-key, becuase everyone forgets things sometimes
#+BEGIN_SRC emacs-lisp
(use-package which-key
  :ensure t
  :init (which-key-mode))
#+END_SRC
** rainbow-mode
   Visualise colours inside text
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t)
#+END_SRC
* Helm
  Helm is an autocompletion engine and then some. I use it for a *lot* of stuff
** Helm itself
#+BEGIN_SRC emacs-lisp
  (use-package helm
    :ensure t
    :config
    (setq helm-autoresize-max-height 25
          helm-autoresize-min-height 5
          helm-buffers-fuzzy-matching t
          helm-recentf-fuzzy-match t
          helm-imenu-fuzzy-math t)
    :init
    (helm-mode 1)
    (helm-autoresize-mode 1))
#+END_SRC

** Keybinds
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
        "ff" 'helm-find-files
        "bb" 'helm-buffers-list
        "hm" 'helm-mini
        "hk" 'helm-show-kill-ring)
#+END_SRC
* General Programming
** rainbow-delimiters
   Colour delimiters
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t)

  (add-hook 'prog-mode-hook
    #'rainbow-delimiters-mode)
#+END_SRC
** linum-relitive
#+BEGIN_SRC emacs-lisp
  (use-package linum-relative
    :ensure t)

  (add-hook 'prog-mode-hook
            #'linum-relative-mode)
#+END_SRC
* Config edit/reload
  Anything that's meta-config related (Editing config, re sourcing it etc etc)
** Edit
#+BEGIN_SRC emacs-lisp
  (defun config-visit ()
    (interactive)
    (find-file "~/.emacs.d/config.org"))
  (evil-leader/set-key
    "fee" 'config-visit)
#+END_SRC
** Reload Config
#+BEGIN_SRC emacs-lisp
  (defun config-reload ()
    (interactive)
    (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
  (evil-leader/set-key
    "feR" 'config-reload)
#+END_SRC
