* Rincewind's Emacs
** Disclaimer
This emacs config is constantly in a state of flux. I would not reccomend sourcing it
as a daily driver without providing your own stable base. As much as i hate the phrase I
"Move Fast And Break Things"
** Some notes
This emacs config makes exensive use of both evil mode and use package.

This config also makes usage of org mode babel to extract the emacs lisp from this very same
org mode file and use that. This feature alone is one of the key things that made me drop vim.

I personally am a mostly C/C++ and lisp developer, as such a lot of this config is geared towards
my own specific workflow for these languages.

I am also a student; as such, there is a fair bit
of org mode config, as well as LaTeX and markdown for prose and notes respectivley.

There are also probably a few other language-specific setups in this config file that i use
less frequently. They include languages like bash/zsh, ruby and assembley.
** Inspiration
I would like to thank daedreth for his emacs config (https://github.com/daedreth/UncleDavesEmacs/)
which inspired me to use org mode for my config, as well as for putting up with my dumb beginner questions.

I would also like to thank hlissner for his Doom Emacs config, which also inspired me to switch from
vim to emacs with his wonderfull and very, very evil config. https://github.com/hlissner/doom-emacs
* Evil
  I use evil mode becuase i still firmly beleive that modal editing is the best editing experience and i want to keep that in emacs
** Disable integration for evil collection
#+BEGIN_SRC emacs-lisp
  (setq evil-want-integration nil)
#+END_SRC
** evil-leader
   Use evil leader to replicate Leader Key functionality. Leader is mapped on <SPC>
#+BEGIN_SRC emacs-lisp
  (use-package evil-leader
    :ensure t
    :init (setq evil-leader/in-all-states t) (global-evil-leader-mode)
    :config (evil-leader/set-leader "<SPC>"))
#+END_SRC
** evil itself
   Load evil mode
#+BEGIN_SRC emacs-lisp
  (use-package evil
    :ensure t
    :config
    (evil-mode 1))
#+END_SRC
** evil-escape
   Add an escape on all modes by hitting fd in quick succession
#+BEGIN_SRC emacs-lisp
  (use-package evil-escape
    :ensure t
    :diminish evil-escape-mode
    :init
    (evil-escape-mode))
#+END_SRC
** evil-collection
   A bunch of community contributed sane keybinds for many, many modes
#+BEGIN_SRC emacs-lisp
(use-package evil-collection
  :after evil
  :ensure t
  :config
  (evil-collection-init))
#+END_SRC
** Window keybinds
   Some keybindings for window management
*** Splits
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
    "w/" 'evil-window-vsplit)
  (evil-leader/set-key
    "w-" 'evil-window-split)
#+END_SRC
*** Deletes
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
    "wd" 'evil-window-delete)
  (evil-leader/set-key
    "wq" 'kill-buffer-and-window)
  (evil-leader/set-key
    "wo" 'delete-other-windows)
#+END_SRC
*** Moves
#+BEGIN_SRC emacs-lisp
  (define-key evil-normal-state-map
    (kbd "C-w <left>") 'evil-window-left)

  (define-key evil-normal-state-map
    (kbd "C-w <right>") 'evil-window-right)

  (define-key evil-normal-state-map
    (kbd "C-w <up>") 'evil-window-up)

  (define-key evil-normal-state-map
    (kbd "C-w <down>") 'evil-window-down)
#+END_SRC
** Buffer keybinds
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
    "bd" 'kill-this-buffer)
  (evil-leader/set-key
    "bq" 'kill-buffer-and-window)
#+END_SRC
** Help Keybinds
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
    "hdv" 'describe-variable)
  (evil-leader/set-key
    "hdf" 'describe-function)
#+END_SRC
** Global keboard-escape-quit
   This is just a little tweak becuase i dont use escape for anything aside from mashing to quit stuff
#+BEGIN_SRC emacs-lisp
  (global-set-key (kbd "<escape>") 'keyboard-escape-quit)
#+END_SRC
* QOL/Emacs core
  Quality of life packages and other miscelany that i find useful
** Start emacs in server mode
#+BEGIN_SRC emacs-lisp
  (server-start)
#+END_SRC
** which-key
   Enable which-key, becuase everyone forgets things sometimes
#+BEGIN_SRC emacs-lisp
  (use-package which-key
    :ensure t
    :diminish which-key-mode
    :init (which-key-mode))
#+END_SRC
** rainbow-mode
   Visualise colours inside text
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-mode
    :ensure t)
#+END_SRC
** async
   Allow for async processes in emacs. Useful
#+BEGIN_SRC emacs-lisp
  (use-package async
    :ensure t
    :init (dired-async-mode 1))
#+END_SRC
** Shackle
   Stuff like helm are not well behaved (at least, in the way i want) shackle lets me hack around it
#+BEGIN_SRC emacs-lisp
  (use-package shackle
    :ensure t)
#+END_SRC
** Show cursor position
   Org, latex and other modes disable relative-linum, this allows us to always have our cursor position in all modes
#+BEGIN_SRC emacs-lisp
  (setq line-number-mode t)
  (setq column-number-mode t)
#+END_SRC
* Helm
  Helm is an autocompletion engine and then some. I use it for a *lot* of stuff
** Helm itself
#+BEGIN_SRC emacs-lisp
  (use-package helm
    :ensure t
    :diminish helm-mode
    :config
    (setq helm-autoresize-max-height 0   ;; Required
          helm-autoresize-min-height 25  ;; Default to 25% frame size
          helm-buffers-fuzzy-matching t  ;; Fuzzy match buffer list
          helm-recentf-fuzzy-match t     ;; Fuzzy match recent list
          helm-imenu-fuzzy-match t       ;; Fuzzy match imenu
          helm-split-window-inside-p t)  ;; Prevent helm from taking over buffers 
    :init
    (helm-mode 1)
    (helm-autoresize-mode 1))
#+END_SRC
** Keybinds
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
        "ff" 'helm-find-files
        "bb" 'helm-buffers-list
        "hm" 'helm-mini
        "hk" 'helm-show-kill-ring)

  ;; Switch tab and return's usage
  (define-key helm-map (kbd "TAB") #'helm-execute-persistent-action)
  (define-key helm-map (kbd "<tab>") #'helm-execute-persistent-action)
  (define-key helm-map (kbd "C-z") #'helm-select-action)
#+END_SRC
** Shackle helm
Helm likes to take over splits. Shackle is a workaround to fix this and force it to
open a new buffer on the bottom of the screen. This does however break stuff that requires
a full frame. But i dont use any of that. Taken from https://emacs.stackexchange.com/questions/14253/how-to-stop-helm-deleting-vertical-split-when-opening-helm-buffer
#+BEGIN_SRC emacs-lisp
  (setq helm-display-function #'pop-to-buffer)
  (setq shackle-rules '(("\\`\\*helm.*?\\*\\'" :regexp t :align t :ratio 0.25)))
  (shackle-mode)
#+END_SRC
** lean helm window
#+BEGIN_SRC emacs-lisp
  (defvar helm-source-header-default-background
      (face-attribute 'helm-source-header :background))
    (defvar helm-source-header-default-foreground
      (face-attribute 'helm-source-header :foreground))
    (defvar helm-source-header-default-box
      (face-attribute 'helm-source-header :box))
    (defvar helm-source-header-default-height
  (face-attribute 'helm-source-header :height))
#+END_SRC
* Projectile
Projectile is a project manager in emacs. It's amazing
** Enable projectile and make it global
#+BEGIN_SRC emacs-lisp
  (use-package projectile
    :ensure t
    :delight '(:eval (concat " " (projectile-project-name)))
    :init
    (projectile-mode 1))
#+END_SRC
** Projectile keybindings
*** Make
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key
    "pm" 'projectile-compile-project)
#+END_SRC
* General Programming
** yasnippet
Snippets == Good. Yasnippet is actually probably one of the best snippet toolkits i've ever used and made me start using them a lot more
#+BEGIN_SRC emacs-lisp
  (use-package yasnippet
    :ensure t
    :delight (yas-minor-mode "YAS"))
#+END_SRC
** Flycheck
God damn. Flycheck is *fucking amazing*. This along with Rtags/Company was the final nail in vim's coffin for me
#+BEGIN_SRC emacs-lisp
  (use-package flycheck
    :ensure t
    :delight (flycheck-mode "FC"))
#+END_SRC
** Company-mode
As stated with flycheck, company is amazing. It's a great autocompletion system. It's a bit heavy
(compared to AC that is) but that's not a major concern for me.
#+BEGIN_SRC emacs-lisp
  (use-package company
    :ensure t
    :delight (company-mode "C")
    :config
    (setq company-minimum-prefix-length 3)
    (delete 'company-backends 'company-clang))
#+END_SRC
** Magit
Apparently this will revolutionise the way i use git. Let's find out
#+BEGIN_SRC emacs-lisp
  (use-package magit
    :ensure t)
  (use-package evil-magit
    :ensure t)
#+END_SRC
** Programming Conviniences
   This section is a bunch of small stuff that makes programming in emacs /just/ that bit nicer
*** rainbow-delimiters
   Colour delimiters, makes using lisp much more cozy
#+BEGIN_SRC emacs-lisp
  (use-package rainbow-delimiters
    :ensure t
    :config
    (add-hook 'prog-mode-hook 'rainbow-delimiters-mode))
#+END_SRC
*** linum-relitive
   Relative line numbers are blessed for vim and evil mode.
#+BEGIN_SRC emacs-lisp
  (use-package linum-relative
    :ensure t
    :config
    (setq linum-relative-current-symbol "")
    (add-hook 'prog-mode-hook 'linum-relative-mode))
#+END_SRC
*** Subword mode
   Makes camelcase a sepperator for jumps
#+BEGIN_SRC emacs-lisp
  (global-subword-mode 1)
#+END_SRC
*** Show Paren Mode
#+BEGIN_SRC emacs-lisp
  (show-paren-mode 1)
#+END_SRC
*** Hungry Delete
Hungry deletion because emacs doesn't do it by default
#+BEGIN_SRC emacs-lisp
  (use-package hungry-delete
    :ensure t
    :delight
    :config
      (global-hungry-delete-mode))
#+END_SRC
*** Electric mode
#+BEGIN_SRC emacs-lisp
  (setq electric-pair-pairs '(
                             (?\{ . ?\})
                             (?\( . ?\))
                             (?\[ . ?\])
                             (?\" . ?\")
                             ))

  (electric-pair-mode t)
#+END_SRC
*** Hilight-indent-guides
#+BEGIN_SRC emacs-lisp
  (use-package highlight-indent-guides
    :ensure t
    :config
    (setq highlight-indent-guides-method 'character)
    (setq highlight-indent-guides-character ?\|)
    (add-hook 'prog-mode-hook 'highlight-indent-guides-mode))
#+END_SRC
*** 100char limit
#+BEGIN_SRC emacs-lisp
  (use-package column-enforce-mode
    :ensure t
    :delight
    :config
    (add-hook 'prog-mode-hook 'column-enforce-mode)
    (setq column-enforce-column 100))
#+END_SRC
* C/C++
** Enable yas
Since i dont use yas as a global mode, add it as a hook on loading C/C++
#+BEGIN_SRC emacs-lisp
  (add-hook 'c++-mode-hook 'yas-minor-mode)
  (add-hook 'c-mode-hook 'yas-minor-mode)
#+END_SRC
** C/C++ Flycheck Settings
Set my C++ language standard, as well as -Wall.
Also add hooks on C/C++ mode to load flycheck
   #+BEGIN_SRC emacs-lisp
     (setq flycheck-clang-language-standard "c++2a")
     (setq flycheck-clang-warnings '("-Wall"))
     (add-hook 'c++-mode-hook 'flycheck-mode)
     (add-hook 'c-mode-hook 'flycheck-mode)
   #+END_SRC
** Company Irony
Uses company-c-headers to add header completion to company
Enables irony-mode as a clang backend
#+BEGIN_SRC emacs-lisp
  (use-package irony
    :ensure t
    :config
    (add-hook 'c++-mode-hook 'irony-mode)
    (add-hook 'c-mode-hook 'irony-mode)
    (add-hook 'irony-mode-hook 'irony-cdb-autosetup-compile-options))

  (use-package company-irony
    :ensure t
    :config
    (add-to-list 'company-backends 'company-irony))

  (use-package company-irony-c-headers
    :ensure t
    :config
    (add-to-list 'company-backends 'company-irony-c-headers))

  #+END_SRC
** Rtags
Again, this is one of those packages that cemented the reason to switch to emacs in my mind.
Rtags is fucking bae
#+BEGIN_SRC emacs-lisp
  (use-package rtags
    :ensure t)

  (add-hook 'c-mode-hook 'rtags-start-process-unless-running)
  (add-hook 'c++-mode-hook 'rtags-start-process-unless-running)
#+END_SRC
** clang-format
#+BEGIN_SRC emacs-lisp
  (use-package clang-format
    :ensure t
    :config
    (setq clang-format-style "~/programming/.clang-format"))

  (evil-leader/set-key-for-mode 'c++-mode
    "mfb" 'clang-format-buffer
    "mfr" 'clang-format-region)

  (which-key-declare-prefixes-for-mode 'c++-mode
    "SPC m"   "C++"
    "SPC m f" "format")

  (evil-leader/set-key-for-mode 'c-mode
    "mfb" 'clang-format-buffer
    "mfr" 'clang-format-region)

  (which-key-declare-prefixes-for-mode 'c-mode
    "SPC m"   "C"
    "SPC m f" "format")
#+END_SRC
* lisps
** Slime
#+BEGIN_SRC emacs-lisp
  (use-package slime
    :ensure t
    :config
    (setq inferior-lisp-program "/usr/bin/sbcl")
    (setq slime-contribs '(slime-fancy)))
#+END_SRC
** Company
#+BEGIN_SRC emacs-lisp
  (use-package slime-company
    :ensure t
    :init
    (require 'company)
    (slime-setup '(slime-fancy slime-company)))

  (add-hook 'lisp-mode-hook 'company-mode)
  (add-hook 'emacs-lisp-mode-hook 'company-mode)
#+END_SRC
** yas
#+BEGIN_SRC emacs-lisp
  (add-hook 'emacs-lisp-mode-hook 'yas-minor-mode)
  (add-hook 'lisp-mode-hook 'yas-minor-mode)
#+END_SRC
** Keybinds
#+BEGIN_SRC emacs-lisp
  (evil-leader/set-key-for-mode 'lisp-mode
    "m'" 'slime
    "mef" 'slime-eval-defun
    "meb" 'slime-eval-buffer)

  (which-key-declare-prefixes-for-mode 'lisp-mode
    "SPC m" "lisp"
    "SPC m e" "eval")
#+END_SRC
* Ruby
** enh-ruby-mode
#+BEGIN_SRC emacs-lisp
  (use-package enh-ruby-mode
    :ensure t
    :config
    (add-to-list 'auto-mode-alist
               '("\\(?:\\.rb\\|ru\\|rake\\|thor\\|jbuilder\\|gemspec\\|podspec\\|/\\(?:Gem\\|Rake\\|Cap\\|Thor\\|Vagrant\\|Guard\\|Pod\\)file\\)\\'" . enh-ruby-mode)))
#+END_SRC
** robe
#+BEGIN_SRC emacs-lisp
  (use-package robe
    :ensure t
    :config
    (add-hook 'enh-ruby-mode-hook 'robe-mode)
    (add-hook 'enh-ruby-mode-hook 'company-mode)
    (eval-after-load 'company
      '(push 'company-robe company-backends)))
#+END_SRC
* Markups
** Org
  Org is amazing. Config and packages for it go here. If you dont like org, i dont want to be your freind
*** Org Bullets
   Add some pretty bullet points instead of *s everywhere
#+BEGIN_SRC emacs-lisp
  (use-package org-bullets
    :ensure t
    :config
    (add-hook 'org-mode-hook (lambda () (org-bullets-mode))))
#+END_SRC
*** org-evil
#+BEGIN_SRC emacs-lisp
  (use-package org-evil
    :ensure t)
#+END_SRC
*** Add evil source editing
   A few evil keybinds to make editing source for this config easier and more vim-y
#+BEGIN_SRC emacs-lisp
  ;; Edit current org source block
  (evil-leader/set-key-for-mode
    'org-mode "es" 'org-edit-special)

  ;; Exit org source mode
  (evil-define-minor-mode-key
    'normal 'org-src-mode " q" 'org-edit-src-exit)
#+END_SRC
*** Emacs lisp src template
#+BEGIN_SRC emacs-lisp
  (add-to-list 'org-structure-template-alist
                 '("el" "#+BEGIN_SRC emacs-lisp\n?\n#+END_SRC"))
#+END_SRC
** markdown
#+BEGIN_SRC emacs-lisp
  (use-package markdown-mode
    :ensure t
    :commands (markdown-mode gfm-mode)
    :mode (("README\\.md\\'" . gfm-mode)
           ("\\.md\\'" . markdown-mode)
           ("\\.markdown\\'" . markdown-mode))
    :init (setq markdown-command "multimarkdown"))
#+END_SRC
** auctex
#+BEGIN_SRC emacs-lisp
  (use-package tex
    :ensure auctex)
#+END_SRC
** Flyspell
   Not exactly a markup. But this is the only time i use it
#+BEGIN_SRC emacs-lisp
  (use-package flyspell
    :config
    (add-hook 'org-mode-hook 'flyspell-mode)
    (add-hook 'LaTeX-mode-hook 'flyspell-mode))
#+END_SRC
* Misc
  Small misc tweaks and packages that dont need their own category
** change yes-or-no to y-or-n
#+BEGIN_SRC emacs-lisp
  (defalias 'yes-or-no-p 'y-or-n-p)
#+END_SRC
** Fix emacs shitty default scrolling
#+BEGIN_SRC emacs-lisp
  (setq scroll-conservatively 101)
#+END_SRC
** Disable ring bell because it's spooky
#+BEGIN_SRC emacs-lisp
  (setq ring-bell-function 'ignore) 
#+END_SRC
** Enable line hilight
#+BEGIN_SRC emacs-lisp
  (when window-system (global-hl-line-mode t))
#+END_SRC
** Disable backups and autosaves
#+BEGIN_SRC emacs-lisp
  (setq make-backup-file nil)
  (setq auto-save-default nil)
#+END_SRC
** Enforce UTF-8
   Because it's CURRENT YEAR
#+BEGIN_SRC emacs-lisp
  (setq locale-coding-system 'utf-8)
  (set-terminal-coding-system 'utf-8)
  (set-keyboard-coding-system 'utf-8)
  (set-selection-coding-system 'utf-8)
  (prefer-coding-system 'utf-8)
#+END_SRC
** Config edit/reload
  Anything that's meta-config related (Editing config, re sourcing it etc etc)
*** Edit
#+BEGIN_SRC emacs-lisp
  (defun config-visit ()
    (interactive)
    (find-file "~/.emacs.d/config.org"))
  (evil-leader/set-key
    "fee" 'config-visit)
#+END_SRC
*** Reload Config
#+BEGIN_SRC emacs-lisp
  (defun config-reload ()
    (interactive)
    (org-babel-load-file (expand-file-name "~/.emacs.d/config.org")))
  (evil-leader/set-key
    "feR" 'config-reload)
#+END_SRC
* Rice
  The Structure And Interpretation Of Riced Text Editors
** GUI Bullshit
*** Disable toolbar
#+BEGIN_SRC emacs-lisp
(tool-bar-mode -1)
#+END_SRC
*** Disable menu bar
#+BEGIN_SRC emacs-lisp
(menu-bar-mode -1)
#+END_SRC
*** Disable scroll bar
#+BEGIN_SRC emacs-lisp
(scroll-bar-mode -1)
#+END_SRC
*** Disable default emacs startup screen
#+BEGIN_SRC emacs-lisp
(setq inhibit-startup-message t)
#+END_SRC
** Dashboard
   Dashboard is great. It looks nice and it's convinient.
#+BEGIN_SRC emacs-lisp
  (use-package dashboard
    :ensure t
    :config
    (dashboard-setup-startup-hook)
    (setq dashboard-items '((recents . 10)))
    (setq dashboard-startup-banner "~/.emacs.d/logo.png")
    (setq dashboard-banner-logo-title "Structure And Interepretation of Riced Text Editors"))
#+END_SRC
** spaceline
   The default emacs modeline is horrible. Powerline is lacking. Spaceline is good
#+BEGIN_SRC emacs-lisp
  (use-package spaceline
    :ensure t
    :config
    (require 'spaceline-config)
    (setq-default powerline-default-seperator (quote arrow-fade))
    (spaceline-spacemacs-theme))
#+END_SRC
** Diminish
   Diminish is a useful package that hides entrys on the minor mode line. Use package has built in support for it
#+BEGIN_SRC emacs-lisp
  (use-package diminish
    :ensure t)
#+END_SRC
*** Diminishes
    Diminish a bunch of things that dont have use-package diminishes
#+BEGIN_SRC emacs-lisp
  (diminish 'undo-tree-mode)
  (diminish 'subword-mode)
  (diminish 'linum-relative-mode)
  (diminish 'abbrev-mode)
#+END_SRC
** Delight
Diminish is cool and all, but delight has better support for name replacements
#+BEGIN_SRC emacs-lisp
  (use-package delight
    :ensure t)
#+END_SRC
** Prevent Cursor Blinking
#+BEGIN_SRC emacs-lisp
  (blink-cursor-mode 0)
#+END_SRC

